# Site settings
title: "AZ-204 Desarrollo de soluciones para Microsoft Azure"
description: "Curso AZ-204T00 en EducacionIT"
github_username: ChristianGrimberg
author: "Christian Grimberg"

# Build settings
#theme: jekyll-theme-cayman
remote_theme: ChristianGrimberg/Jekyll-Theme
header_pages:
  - index.html
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
show_downloads: false
