# Site settings
title: "AZ-204T00 Developing Solutions for Microsoft Azure"
description: "Curso AZ-204T00 en EducacionIT"
github_username: ChristianGrimberg
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman