# Site settings
title: "AZ-204T00 Developing Solutions for Microsoft Azure"
description: "Curso oficial de Microsoft en EducacionIT"
github_username: ChristianGrimberg

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed